// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmwpwRgfkpI9G5gtTOe9bkm2BAYnS0Kcw',
    appId: '1:390240531270:web:cd92b4b04b6e76147eab47',
    messagingSenderId: '390240531270',
    projectId: 'focusflow-productivityapp',
    authDomain: 'focusflow-productivityapp.firebaseapp.com',
    storageBucket: 'focusflow-productivityapp.firebasestorage.app',
    measurementId: 'G-BCNKG69FDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1EX-9yfxLE0tuKBGAT11y62v2EMkuxUo',
    appId: '1:390240531270:android:a513b06f86d3c7407eab47',
    messagingSenderId: '390240531270',
    projectId: 'focusflow-productivityapp',
    storageBucket: 'focusflow-productivityapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATk0ia9bA1-pk28Kfw9dhKvAoj1n6qf7k',
    appId: '1:390240531270:ios:e7c4222ce120675e7eab47',
    messagingSenderId: '390240531270',
    projectId: 'focusflow-productivityapp',
    storageBucket: 'focusflow-productivityapp.firebasestorage.app',
    androidClientId: '390240531270-ldds50lc95qrjiga84btqqtvvl815e0o.apps.googleusercontent.com',
    iosClientId: '390240531270-o7v2gej5khvtpdg89kllqmqupihqs6tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATk0ia9bA1-pk28Kfw9dhKvAoj1n6qf7k',
    appId: '1:390240531270:ios:e7c4222ce120675e7eab47',
    messagingSenderId: '390240531270',
    projectId: 'focusflow-productivityapp',
    storageBucket: 'focusflow-productivityapp.firebasestorage.app',
    androidClientId: '390240531270-ldds50lc95qrjiga84btqqtvvl815e0o.apps.googleusercontent.com',
    iosClientId: '390240531270-o7v2gej5khvtpdg89kllqmqupihqs6tk.apps.googleusercontent.com',
    iosBundleId: 'com.example.productivityTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmwpwRgfkpI9G5gtTOe9bkm2BAYnS0Kcw',
    appId: '1:390240531270:web:658fd247af2164ac7eab47',
    messagingSenderId: '390240531270',
    projectId: 'focusflow-productivityapp',
    authDomain: 'focusflow-productivityapp.firebaseapp.com',
    storageBucket: 'focusflow-productivityapp.firebasestorage.app',
    measurementId: 'G-QWT41GH4LP',
  );

}